## Telegram

#### Useful links:
- [Telegram Official API](https://core.telegram.org/api)
- [Manage Apps - Get API ID and API Hash](https://my.telegram.org)
- [Telethon - How to install](https://docs.telethon.dev/en/stable/basic/installation.html)
- [Telethon - Telegram Client](https://docs.telethon.dev/en/stable/modules/client.html)

In [1]:
# requirements
%pip install pandas python-dotenv aiohttp cryptg hachoir Pillow Telethon

Requirement already satisfied: pandas in /home/lucas/.pyenv/versions/3.13.5/envs/transparency-index/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: python-dotenv in /home/lucas/.pyenv/versions/3.13.5/envs/transparency-index/lib/python3.13/site-packages (1.2.1)
Collecting aiohttp
  Downloading aiohttp-3.13.2-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (8.1 kB)
Collecting cryptg
  Downloading cryptg-0.5.2-cp313-cp313-manylinux_2_28_x86_64.whl.metadata (1.6 kB)
Collecting hachoir
  Downloading hachoir-3.3.0-py3-none-any.whl.metadata (2.9 kB)
Collecting Pillow
  Downloading pillow-12.0.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.8 kB)
Collecting Telethon
  Downloading telethon-1.41.2-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: numpy>=1.26.0 in /home/lucas/.pyenv/versions/3.13.5/envs/transparency-index/lib/python3.13/site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/lucas/.pyenv/versions/3.13.5/envs/transparency-index/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/lucas/.pyenv/versions/3.13.5/envs/transparency-index/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/lucas/.pyenv/versions/3.13.5/envs/transparency-index/lib/python3.13/site-packages (from pandas) (2025.2)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp)
  Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in /home/lucas/.pyenv/versions/3.13.5/envs/transparency-index/lib/python3.13/site-packages (from aiohttp) (25.4.0)
Collecting frozenlist>=1.1.1 (from aiohttp)
  Downloading frozenlist-1.8.0-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (20 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp)
  Downloading multidict-6.7.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting propcache>=0.2.0 (from aiohttp)
  Downloading propcache-0.4.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp)
  Downloading yarl-1.22.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (75 kB)
Requirement already satisfied: idna>=2.0 in /home/lucas/.pyenv/versions/3.13.5/envs/transparency-index/lib/python3.13/site-packages (from yarl<2.0,>=1.17.0->aiohttp) (3.11)
Collecting pyaes (from Telethon)
  Using cached pyaes-1.6.1.tar.gz (28 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: rsa in /home/lucas/.pyenv/versions/3.13.5/envs/transparency-index/lib/python3.13/site-packages (from Telethon) (4.9.1)
Requirement already satisfied: six>=1.5 in /home/lucas/.pyenv/versions/3.13.5/envs/transparency-index/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: pyasn1>=0.1.3 in /home/lucas/.pyenv/versions/3.13.5/envs/transparency-index/lib/python3.13/site-packages (from rsa->Telethon) (0.6.1)
Downloading aiohttp-3.13.2-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 67.4 MB/s  0:00:00
Downloading multidict-6.7.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (254 kB)
Downloading yarl-1.22.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (377 kB)
Downloading cryptg-0.5.2-cp313-cp313-manylinux_2_28_x86_64.whl (255 kB)
Downloading hachoir-3.3.0-py3-none-any.whl (650 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 650.4/650.4 kB 58.5 MB/s  0:00:00
Downloading pillow-12.0.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (7.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 75.3 MB/s  0:00:00
Downloading telethon-1.41.2-py3-none-any.whl (744 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 744.9/744.9 kB 60.4 MB/s  0:00:00
Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading frozenlist-1.8.0-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (234 kB)
Downloading propcache-0.4.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (204 kB)
Building wheels for collected packages: pyaes
  Building wheel for pyaes (pyproject.toml) ... done
  Created wheel for pyaes: filename=pyaes-1.6.1-py3-none-any.whl size=26422 sha256=63d60d7c5012a5ff77f3039a586a46c7bf0b212847a5f711f85f1d3ddafe61ab
  Stored in directory: /home/lucas/.cache/pip/wheels/cf/2b/cc/2cd1fc992150692e118eb782ca44536ebc2b566823353085ba
Successfully built pyaes
Installing collected packages: pyaes, hachoir, propcache, Pillow, multidict, frozenlist, cryptg, aiohappyeyeballs, yarl, Telethon, aiosignal, aiohttp
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12/12 [aiohttp];237m━━━ 11/12 [aiohttp]
Successfully installed Pillow-12.0.0 Telethon-1.41.2 aiohappyeyeballs-2.6.1 aiohttp-3.13.2 aiosignal-1.4.0 cryptg-0.5.2 frozenlist-1.8.0 hachoir-3.3.0 multidict-6.7.0 propcache-0.4.1 pyaes-1.6.1 yarl-1.22.0
Note: you may need to restart the kernel to use updated packages.

In [1]:
import os
import json
import pickle
import hashlib

from datetime import datetime, timezone
from time import sleep

import asyncio
import pandas as pd

from dotenv import load_dotenv
from telethon import TelegramClient
from telethon.tl.types import PeerChannel, PeerUser, InputPeerEmpty, InputMessagesFilterEmpty
from telethon.tl import functions, patched

In [2]:
# environment variables
load_dotenv()
FILENAME = os.getenv("FILENAME")
API_ID = os.getenv("API_ID")
API_HASH = os.getenv("API_HASH")

In [3]:
# API connection
api_client = TelegramClient(session=FILENAME, api_id=API_ID, api_hash=API_HASH)

In [4]:
await api_client.start()

In [133]:
await api_client.disconnect()

### SPECIAL CRITERIA

**SC1: Does the platform offer an API for collecting public user-generated content data?**

*This item verifies whether the platform provides an API with at least one endpoint for programmatically extracting public user-generated content to the users’ infrastructure. Public user-generated content is defined here as any publicly visible publication accessible by any platform user. The assessment should verify that the endpoint allows retrieval and storage of this content without requiring privileged or internal access beyond standard developer registration.*

In [20]:
peer_channel = PeerChannel(channel_id=1593453357)# object that identifies a channel

async def get_messages_from_channel(api_client: TelegramClient, peer: PeerChannel, limit: int = 5):
    # method accessing the endpoint for getting messages. By default, returns messages from newest to oldest
    return await api_client.get_messages(
        entity=peer,# object for identifying a group, channel or user
        limit=limit# maximum number of messages to retrieve
    )

messages = await asyncio.create_task(get_messages_from_channel(api_client=api_client, peer=peer_channel))

[{'id': m.id, 'peer_id': m.peer_id.channel_id, 'date': m.date, 'message': m.message} for m in messages]

[{'id': 6326,
  'peer_id': 1593453357,
  'date': datetime.datetime(2025, 7, 6, 20, 25, 15, tzinfo=datetime.timezone.utc),
  'message': '"Trece Noches" 1991/92.\n\nAntonio Gala y Jesús Quintero predicen con precisión el futuro digital.\n\n✅ t.me/noticias2030'},
 {'id': 6325,
  'peer_id': 1593453357,
  'date': datetime.datetime(2025, 7, 4, 17, 29, tzinfo=datetime.timezone.utc),
  'message': '👆🏻👆🏻👆🏻'},
 {'id': 6324,
  'peer_id': 1593453357,
  'date': datetime.datetime(2025, 7, 4, 17, 25, 13, tzinfo=datetime.timezone.utc),
  'message': ''},
 {'id': 6323,
  'peer_id': 1593453357,
  'date': datetime.datetime(2025, 7, 4, 17, 25, 12, tzinfo=datetime.timezone.utc),
  'message': 'Las dos caras en Alcalá de Henares tras la violación de una chica de 21 años frente a un centro de acogida de inmigrantes y el descomunal aumento de la delincuencia.\n\n"Pobrecitos, es que llevan cinco años sin..."\n\n✅ t.me/noticias2030'},
 {'id': 6322,
  'peer_id': 1593453357,
  'date': datetime.datetime(2025, 7, 4, 17, 11, 17, tzinfo=datetime.timezone.utc),
  'message': ''}]

### ACCESSIBILITY

**OC1: Does the platform offer any type of access to non-public data (e.g., private groups, not direct messages) to approved researchers?**

*This item verifies whether, beyond the retrieval and extraction of public user-generated content data, the API permits the extraction of any data from non-public content, such as posts and comments in private groups or discussion forums, subject to the implementation of adequate data hashing measures and specific researcher approval. The assessment should confirm that the API provides such access measures, either through specific endpoints or other controlled access mechanisms.*

No. No official researcher access program exists.<br>Researchers use the same public APIs as other developers to access publicly available channels and groups.

**OC2: Can the requested data be extracted directly from the platform’s API response?**

*This item verifies whether the API returns structured data directly in its response, rather than only providing a redirect link to the data. Audiovisual media (e.g., images, videos, and audio) are excluded from this assessment. The assessment should check sample API responses to confirm that the requested public data is included in the returned payload itself.*

In [19]:
peer_channel = PeerChannel(channel_id=1593453357)# object that identifies a channel

async def get_messages_from_channel(api_client: TelegramClient, peer: PeerChannel, limit: int = 5):
    # method accessing the endpoint for getting messages. By default, returns messages from newest to oldest
    return await api_client.get_messages(
        entity=peer,# object for identifying a group, channel or user
        limit=limit# maximum number of messages to retrieve
    )

messages = await asyncio.create_task(get_messages_from_channel(api_client=api_client, peer=peer_channel))

[{'id': m.id, 'peer_id': m.peer_id.channel_id, 'date': m.date, 'message': m.message} for m in messages]

[{'id': 6326,
  'peer_id': 1593453357,
  'date': datetime.datetime(2025, 7, 6, 20, 25, 15, tzinfo=datetime.timezone.utc),
  'message': '"Trece Noches" 1991/92.\n\nAntonio Gala y Jesús Quintero predicen con precisión el futuro digital.\n\n✅ t.me/noticias2030'},
 {'id': 6325,
  'peer_id': 1593453357,
  'date': datetime.datetime(2025, 7, 4, 17, 29, tzinfo=datetime.timezone.utc),
  'message': '👆🏻👆🏻👆🏻'},
 {'id': 6324,
  'peer_id': 1593453357,
  'date': datetime.datetime(2025, 7, 4, 17, 25, 13, tzinfo=datetime.timezone.utc),
  'message': ''},
 {'id': 6323,
  'peer_id': 1593453357,
  'date': datetime.datetime(2025, 7, 4, 17, 25, 12, tzinfo=datetime.timezone.utc),
  'message': 'Las dos caras en Alcalá de Henares tras la violación de una chica de 21 años frente a un centro de acogida de inmigrantes y el descomunal aumento de la delincuencia.\n\n"Pobrecitos, es que llevan cinco años sin..."\n\n✅ t.me/noticias2030'},
 {'id': 6322,
  'peer_id': 1593453357,
  'date': datetime.datetime(2025, 7, 4, 17, 11, 17, tzinfo=datetime.timezone.utc),
  'message': ''}]

**OC4: Does the platform’s API offer an endpoint for extracting data from an individual publication?**

*This item verifies whether it is possible to collect data from a specific public post on the platform using a unique identifier, rather than relying on search terms or other filters. The assessment should review the API documentation and test available endpoints to confirm that an individual publication can be retrieved directly by its unique identifier.*

In [7]:
message_id = 6323
peer_channel = PeerChannel(channel_id=1593453357)# object that identifies a channel

async def get_specific_message_from_channel(api_client: TelegramClient, peer: PeerChannel, msg_id: int):
    # method accessing the endpoint for getting messages.
    return await api_client.get_messages(
        entity=peer,# object for identifying a group, channel or user
        ids=msg_id,# list of message IDs to fetch
    )

message = await asyncio.create_task(get_specific_message_from_channel(api_client=api_client, peer=peer_channel, msg_id=message_id))

{'id': message.id, 'peer_id': message.peer_id.channel_id, 'date': message.date, 'message': message.message}

{'id': 6323,
 'peer_id': 1593453357,
 'date': datetime.datetime(2025, 7, 4, 17, 25, 12, tzinfo=datetime.timezone.utc),
 'message': 'Las dos caras en Alcalá de Henares tras la violación de una chica de 21 años frente a un centro de acogida de inmigrantes y el descomunal aumento de la delincuencia.\n\n"Pobrecitos, es que llevan cinco años sin..."\n\n✅ t.me/noticias2030'}

**OC5: Does the platform’s API offer an endpoint for extracting data from an individual author?**

*This item verifies whether it is possible to collect data from public posts made by a specific author, using their username or unique identifier. The assessment should review the API documentation and test relevant endpoints to confirm that data can be retrieved directly for an individual author.*

In [39]:
user_id = # ID removed when uploading to github. We can check the results by it's hash

def hash_user_id(user_id: int):
    return hashlib.sha256(str(user_id).encode('utf-8')).hexdigest()

user_id_hash = hash_user_id(user_id=user_id)
user_id_hash

'ec3ef0c08dca6e0221d24a014660f29ce9054f169d7fceb155b740d298d35000'

In [49]:
peer_channel = PeerChannel(channel_id=1521272409)# object that identifies a channel
peer_user = PeerUser(user_id=user_id)# object that identifies a user

async def get_messages_from_author(api_client: TelegramClient, peer_channel: PeerChannel, peer_user: PeerUser, limit: int = 10):
    # method accessing the endpoint for getting messages.
    return await api_client.get_messages(
        entity=peer_channel,
        from_user=peer_user,
        limit=limit
    )

messages = await asyncio.create_task(get_messages_from_author(api_client=api_client, peer_channel=peer_channel, peer_user=peer_user))

[
    {
        'channel_id': message.peer_id.channel_id,
        'message_author_id_hash': hash_user_id(message.from_id.user_id),
        'msg_is_from_requested_user': hash_user_id(message.from_id.user_id) == user_id_hash
    } for message in messages
]

[{'channel_id': 1521272409,
  'message_author_id_hash': 'ec3ef0c08dca6e0221d24a014660f29ce9054f169d7fceb155b740d298d35000',
  'msg_is_from_requested_user': True},
 {'channel_id': 1521272409,
  'message_author_id_hash': 'ec3ef0c08dca6e0221d24a014660f29ce9054f169d7fceb155b740d298d35000',
  'msg_is_from_requested_user': True},
 {'channel_id': 1521272409,
  'message_author_id_hash': 'ec3ef0c08dca6e0221d24a014660f29ce9054f169d7fceb155b740d298d35000',
  'msg_is_from_requested_user': True},
 {'channel_id': 1521272409,
  'message_author_id_hash': 'ec3ef0c08dca6e0221d24a014660f29ce9054f169d7fceb155b740d298d35000',
  'msg_is_from_requested_user': True},
 {'channel_id': 1521272409,
  'message_author_id_hash': 'ec3ef0c08dca6e0221d24a014660f29ce9054f169d7fceb155b740d298d35000',
  'msg_is_from_requested_user': True}]

**OC6: Does the platform’s API provide an endpoint for extracting data based on search terms?**

*This item verifies whether public user-generated content can be collected via individual or combined search terms, enabling the creation of datasets of posts mentioning those terms. The assessment should test search-related endpoints to confirm that queries using keywords return relevant public posts.*

In [57]:
peer_channel = PeerChannel(channel_id=1593453357)# object that identifies a channel
search_term = 'chocolate'

async def get_search_term_data(api_client: TelegramClient, search_term: str, peer_channel: PeerChannel, limit:int = 10):
    return await api_client.get_messages(
        entity=None,# Perform the search on all chats the account using the API participate in.
        search=search_term,
        limit=limit
    )


messages = await asyncio.create_task(get_search_term_data(api_client=api_client, search_term=search_term, peer_channel=peer_channel))
[ search_term in m.message for m in messages ]

[True, True, True, True, True, True, True, True, True, False]

In [59]:
messages[0].message

'Gaza’s Media Office reported that since last month’s ceasefire, only 4,453 trucks have entered the Strip, far below the 15,600 expected by Wednesday. The enclave is receiving an average of 171 trucks daily, less than a third of the 600 agreed under the ceasefire. Israel continues to block over 350 essential food items, including eggs, meat, fish, dairy, and vegetables, while permitting soft drinks, chocolate, and chips.'

**OC7: Does the API use locale-neutral data representations?**

*This item verifies whether locale-sensitive data (e.g., timestamps, currency, numbers) are returned in a locale-neutral format, or whether relevant locale metadata is included when neutrality is not possible. The assessment should review the API documentation and inspect sample responses to confirm the presence of standardized formats or accompanying metadata.*

In [12]:
message_id = 6323
peer_channel = PeerChannel(channel_id=1593453357)# object that identifies a channel

async def get_specific_message_from_channel(api_client: TelegramClient, peer: PeerChannel, msg_id: int):
    # method accessing the endpoint for getting messages.
    return await api_client.get_messages(
        entity=peer,# object for identifying a group, channel or user
        ids=msg_id,# list of message IDs to fetch
    )

message = await asyncio.create_task(get_specific_message_from_channel(api_client=api_client, peer=peer_channel, msg_id=message_id))

# Date has timezone info
{'id': message.id, 'peer_id': message.peer_id.channel_id, 'date': message.date, 'message': message.message}

{'id': 6323,
 'peer_id': 1593453357,
 'date': datetime.datetime(2025, 7, 4, 17, 25, 12, tzinfo=datetime.timezone.utc),
 'message': 'Las dos caras en Alcalá de Henares tras la violación de una chica de 21 años frente a un centro de acogida de inmigrantes y el descomunal aumento de la delincuencia.\n\n"Pobrecitos, es que llevan cinco años sin..."\n\n✅ t.me/noticias2030'}

### COMPLIANCE

**OC15: Does the platform provide a way to label content that has been generated with artificial intelligence?**

*This item verifies whether the platform automatically flags, or allows users to flag, AI-generated content, and whether this information is given in the API response. The assessment should review the documentation and test API outputs to confirm that these flags are included in the extracted data.*

We found no official policy or technical specification for AI-generated content in Telegram’s API documentation and terms of service.

### COMPLETENESS

**OC16: Can data from a publication’s comments be extracted using the platform’s API?**

*This item verifies whether comment data, including their content, can be extracted when available on the platform, either together with publication data or with a dedicated endpoint. The assessment should test relevant endpoints to confirm that comments are retrievable as structured data. This item does not apply to platforms that do not have commenting features.*

In telegram, a broadcast channel's messages replies are treated and named (in the user interface) as comments. They are displayed in a separate discussion group linked to the original message. But Telethon's "get_messages" method can use the "reply_to" parameter to get those comments/replies from channels.

#### First, let's examine the channel's message with replies

In [73]:
peer_channel = PeerChannel(channel_id=1687584608)# object that identifies a channel
message_with_replies_id = 213253

async def get_specific_message(api_client: TelegramClient, peer: PeerChannel, message_id:int):
    return await api_client.get_messages(
        entity=peer_channel,# object for identifying a group, channel or user
        ids=message_with_replies_id,# list of message IDs to fetch
    )

message_with_replies = await asyncio.create_task(get_specific_message(api_client=api_client, peer=peer_channel, message_id=message_with_replies_id))

In [96]:
message_with_replies.message

'🌩\n\n😎😉😁🙃🤪\n\n\n🅰️🅰️🅰️🅰️\n\n🅰️🅰️🅰️🅰️🅰️🅰️'

In [97]:
anonymous_recent_repliers = [
    {**user.to_dict(), 'user_id': hashlib.sha256(str(user.user_id).encode('utf-8')).hexdigest()}
    for user in message_with_replies.replies.recent_repliers
]

In [98]:
{**message_with_replies.replies.to_dict(), 'recent_repliers': anonymous_recent_repliers}

{'_': 'MessageReplies',
 'replies': 28,
 'replies_pts': 1654122,
 'comments': True,
 'recent_repliers': [{'_': 'PeerUser',
   'user_id': 'ecd1586ea15eb94eb236e4be397ffb5676a1e020aee8e85f4236e793c0ad75f9'},
  {'_': 'PeerUser',
   'user_id': 'a370b9387fd689989884b6694799b6b2a1344c45932632f2526d3a50dcb8107c'},
  {'_': 'PeerUser',
   'user_id': '9e90d23fd715820ca1f2f4253d6dc91acb9c88a1ab3cf8ef6177516faea07914'}],
 'channel_id': 1831447339,
 'max_id': 721621,
 'read_max_id': 721621}

#### Now, let's get the replies from that message

In [99]:
async def get_comments_from_channel_message(api_client: TelegramClient, peer: PeerChannel, message_id: int):
    # method accessing the endpoint for getting messages.
    return await api_client.get_messages(
        entity=peer,# object for identifying a group, channel or user
        reply_to=message_id# get replies (comments, in the case of channels) from this message
    )

comments = await asyncio.create_task(get_comments_from_channel_message(api_client=api_client, peer=peer_channel, message_id=message_with_replies_id))

In [101]:
len(comments), max([c.id for c in comments])

(28, 721621)

In [102]:
[message.message for message in messages]

['Boa noite Anna 🌷 \nBoa noite Livinha 🌺 \nBoa noite Família abençoada do Bem e da Luz 💫',
 'Boa noite.🖖',
 'Boa noite meus amados feliz💜❤️😘😘🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇺🇸',
 'Boa noite! 🐾🐾',
 'Boa noite pessoas queridas',
 'Buenas 🌙😁🙏',
 'Boa noite!🤩💚💛',
 'Abençoada noite ❤️',
 'Cheguei Brasil ❤️',
 'Boa Noite de muita luz',
 'Boa noite, amada família... Paz e Bençãos! 🙏🏽🙏🏽💗🫂🥰💜',
 'Boa noite! 🥰🥰\n💚💛✨💫✨💫',
 'Boa noite🙏🌹🩵😘🇧🇷',
 'Boa noite ❤️ 💫✨️✨️✨️✨️✨️',
 'Boa noite meninas iluminadas!!!\nBoa noite irmãos despertos!!! ✨💫',
 'Boa noite!🙌🤩💜✨',
 'Boa noite a todos!!!💖🌝',
 'Boa Noite!!',
 'Boa noite 💜💜',
 'Boa noite',
 'Boa noite',
 'Boa noite!!   🙌   ❤️',
 'Éramos 6 aguardando abertura do grupo',
 'Boa noite amados 🙌🙏✨✨✨',
 'Boa noite 🌙 a todos.😘',
 'Boa noite 🌹\nÓtima noite a todos ✨🙏🏼✨🙏🏼🎶💃🏼🕺🏼',
 'Boa-noite a todos! 🇧🇷🍾🍿',
 '😍']

**OC17: Can data from temporary content be extracted through the platform’s API?**

*This item verifies whether the platform’s API provides at least one endpoint for collecting data from temporary publications (e.g., stories, ephemeral messages). The assessment should test endpoints to confirm whether this type of short-lived content can be retrieved as structured data before it expires. This item does not apply to platforms that do not have temporary content features.*

First we will collect data from a test group we made

In [8]:
peer_channel = PeerChannel(channel_id=3112265194)

async def get_temporary_data(api_client: TelegramClient, peer: PeerChannel):
    return await api_client.get_messages(
        entity=peer,# object for identifying a group, channel or user
    )

In [132]:
messages = await asyncio.create_task(get_temporary_data(api_client=api_client, peer=peer_channel))

df = pd.DataFrame([{'msg_id': m.id, 'message': m.message, 'date': m.date, 'message retrieved at': datetime.now(tz=timezone.utc).isoformat()} for m in messages])
df

,msg_id,message,date,message retrieved at
0,9,Postando uma segunda mensagem. 2 horas depois ...,2025-11-07 20:14:21+00:00,2025-11-07T20:19:40.070996+00:00
1,8,Ah agora ativei,2025-11-07 18:07:19+00:00,2025-11-07T20:19:40.071008+00:00
2,7,None,2025-11-07 18:07:07+00:00,2025-11-07T20:19:40.071013+00:00
3,5,Mensagem anterior a ativação de mensagens temp...,2025-11-07 16:30:51+00:00,2025-11-07T20:19:40.071017+00:00
4,4,None,2025-11-07 16:30:27+00:00,2025-11-07T20:19:40.071020+00:00
5,3,None,2025-11-05 19:26:43+00:00,2025-11-07T20:19:40.071023+00:00
6,2,Oi,2025-11-05 19:26:32+00:00,2025-11-07T20:19:40.071034+00:00
7,1,None,2025-10-14 13:43:22+00:00,2025-11-07T20:19:40.071037+00:00

Message of ID 7 is the non-user message warning that all messages after this one will be automatically deleted in 1 day (temporary messages activated)
We will make the same request later and check if any message is missing

In [9]:
# Making the same request, days later.
messages = await asyncio.create_task(get_temporary_data(api_client=api_client, peer=peer_channel))

df = pd.DataFrame([{'msg_id': m.id, 'message': m.message, 'date': m.date, 'message retrieved at': datetime.now(tz=timezone.utc).isoformat()} for m in messages])
df

,msg_id,message,date,message retrieved at
0,10,Nova mensagem antes da segunda requisição.\n(N...,2025-11-10 09:13:56+00:00,2025-11-10T09:14:34.407144+00:00
1,7,None,2025-11-07 18:07:07+00:00,2025-11-10T09:14:34.407163+00:00
2,5,Mensagem anterior a ativação de mensagens temp...,2025-11-07 16:30:51+00:00,2025-11-10T09:14:34.407172+00:00
3,4,None,2025-11-07 16:30:27+00:00,2025-11-10T09:14:34.407180+00:00
4,3,None,2025-11-05 19:26:43+00:00,2025-11-10T09:14:34.407187+00:00
5,2,Oi,2025-11-05 19:26:32+00:00,2025-11-10T09:14:34.407194+00:00
6,1,None,2025-10-14 13:43:22+00:00,2025-11-10T09:14:34.407200+00:00

As we can see, the messages of ID 9 and 8 are now deleted and not recoverable. But we were able to collect data from those messages while they were still active on the group.

In [11]:
# Making the same request, days later.
messages = await asyncio.create_task(get_temporary_data(api_client=api_client, peer=peer_channel))

df = pd.DataFrame([{'msg_id': m.id, 'message': m.message, 'date': m.date, 'message retrieved at': datetime.now(tz=timezone.utc).isoformat()} for m in messages])
df

,msg_id,message,date,message retrieved at
0,10,Nova mensagem antes da segunda requisição.\n(N...,2025-11-10 09:13:56+00:00,2025-11-10T09:19:06.116695+00:00
1,7,None,2025-11-07 18:07:07+00:00,2025-11-10T09:19:06.116709+00:00
2,5,Mensagem anterior a ativação de mensagens temp...,2025-11-07 16:30:51+00:00,2025-11-10T09:19:06.116714+00:00
3,4,None,2025-11-07 16:30:27+00:00,2025-11-10T09:19:06.116717+00:00
4,3,None,2025-11-05 19:26:43+00:00,2025-11-10T09:19:06.116720+00:00
5,2,Oi,2025-11-05 19:26:32+00:00,2025-11-10T09:19:06.116723+00:00
6,1,None,2025-10-14 13:43:22+00:00,2025-11-10T09:19:06.116726+00:00

**OC18: Can historical data be extracted through the platform’s API?**

*This item verifies whether the API provides endpoints that allow for a specified time range, going back more than one year from the time the request is made, to collect public user-generated content data. The assessment should review test endpoints to confirm that historical data more than 12 months prior to the analysis can be retrieved.*

In [17]:
offset_date = datetime.fromisoformat('2023-10-01T00:00:00Z')
peer_channel = PeerChannel(channel_id=1593453357)# object that identifies a channel

async def get_messages_from_channel(api_client: TelegramClient, peer: PeerChannel, limit: int = 5):
    # method accessing the endpoint for getting messages. By default, returns messages from newest to oldest
    return await api_client.get_messages(
        entity=peer,# object for identifying a group, channel or user
        offset_date=offset_date,# datetime object. messages prior to this date will be retrieved
        limit=limit# maximum number of messages to retrieve
    )

messages = await asyncio.create_task(get_messages_from_channel(api_client=api_client, peer=peer_channel))

[{'id': m.id, 'peer_id': m.peer_id.channel_id, 'date': m.date, 'message': m.message} for m in messages]

[{'id': 4075,
  'peer_id': 1593453357,
  'date': datetime.datetime(2023, 9, 30, 13, 45, 31, tzinfo=datetime.timezone.utc),
  'message': 'Nauzet Morgade como siempre fantástico 👏🏻👏🏻👏🏻\n\nTrailer del documental donde queda más que patente que, tanto en el incendio de Tenerife como en el de Hawái hubo terrorismo de Estado, crímenes contra el medio ambiente y crímenes de lesa humanidad.\n\nhttps://t.me/NauzetMorgadeOficial/870\n\n✅ t.me/noticias2030'},
 {'id': 4074,
  'peer_id': 1593453357,
  'date': datetime.datetime(2023, 9, 30, 13, 41, 19, tzinfo=datetime.timezone.utc),
  'message': '🇬🇧 Niños jugando pacíficamente con sus pequeños machetes en Leeds, Reino Unido\n\n✅ t.me/noticias2030'},
 {'id': 4073,
  'peer_id': 1593453357,
  'date': datetime.datetime(2023, 9, 30, 11, 49, 20, tzinfo=datetime.timezone.utc),
  'message': ''},
 {'id': 4072,
  'peer_id': 1593453357,
  'date': datetime.datetime(2023, 9, 30, 11, 49, 20, tzinfo=datetime.timezone.utc),
  'message': 'Progresista antiracista y activista contra hombres blancos es violada y asesinada, no imagináis por quién...\n\nLa directora ejecutiva de EcoMap Technologies, Pava Marie LaPere, autodenominada "antirracista" y partidaria de Black Lives Matter que se pronunció contra "la criminalización de los cuerpos negros",  fue asesinada a golpes en su propia casa en Baltimore el lunes por un hombre neցro, quien fue liberado anticipadamente de prisión bajo las políticas de reforma de la justicia penal que ella defendió.\n\nLa fundadora y directora ejecutiva de Fearless, dijo que "LaPere había alcanzado recientemente un hito personal en su empresa: contratar 50% de personas de color y 50% de mujeres", se negaba a contratar a hombres blancos.\n\nhttps://www.informationliberation.com/?id=63992\n\n✅ t.me/noticias2030'},
 {'id': 4071,
  'peer_id': 1593453357,
  'date': datetime.datetime(2023, 9, 30, 11, 36, 32, tzinfo=datetime.timezone.utc),
  'message': ''}]

**OC19: Is the number of requests allowed by the API sufficient for monitoring more than 10,000 publications in 24 hours?**

*This item verifies whether data can be extracted without interruption and losses through the platform’s API for requests that accumulate more than 10,000 publications in 24 hours. The assessment should test the API to confirm that this volume of data can be collected continuously.*

In [75]:
data_dir = "../../data"  # SET PATH
stats_filename = f"br-telegram-UGC-question-19-stats-2025-11-05 20:39:44.894120.json"

with open(f"{data_dir}/{stats_filename}", "r") as fin:
    print(json.load(fin))

{'start_time': '2025-11-05T20:39:44.894120', 'end_time': '2025-11-05T20:41:49.589587', 'total_acquision_time_hour': 0.03, 'total_data_collected': 10100}

In [77]:
data_filename = 'br-telegram-UGC-question-19-data-2025-11-05 20:39:44.894120.pickle'
with open(f'{data_dir}/{data_filename}', 'rb') as fin:
    data = pickle.load(fin)

In [78]:
len(data)

10100

### CONSISTENCY

**OC20: Are the results returned by the API consistently reproducible?**

*This item verifies whether data extracted via the platform’s API at any given time is consistent with other collections performed similarly, including content that has been deleted between collections. The assessment should conduct repeated test queries to confirm the reproducibility of results or ground the response based on recent (less than 2 years) experiments published in peer-reviewed journals.*

Test instructions: Please, develop a test that collects data for 5 times using the same request parameters and the same endpoint. Save each response in separate files.

In [ ]:
offset_date = datetime.fromisoformat('2025-10-01T00:00:00Z')
peer_channel = PeerChannel(channel_id=1593453357)# object that identifies a channel

async def get_reproducible_data(api_client: TelegramClient, peer: PeerChannel, offset_date: datetime, limit: int = 5):
    total_runs = 5 
    for idx in range(total_runs):
        index = idx + 1
        data_dir = "../../data" # SET PATH
        filename = f"br-telegram-UGC-question-20-run-{index}-{datetime.now().strftime('%Y-%m-%dT%H-%M-%S-%f')}.json"
    
        # implement the function here
        response = await api_client.get_messages(
            entity=peer,# object for identifying a group, channel or user
            offset_date=offset_date,# datetime object. messages prior to this date will be retrieved
            limit=limit# maximum number of messages to retrieve
        )
        
        messages = [# convert some of telethon messages fields to a JSON serializable format (e.g. datetime to isoformat)
            {
                'id': m.id,
                'peer_id': m.peer_id.channel_id,
                'date': m.date.isoformat(),
                'message': m.message
            } for m in response
        ]
        
        with open(f"{data_dir}/{filename}", "w") as fout:
            json.dump(messages, fout)
    

await asyncio.create_task(get_reproducible_data(api_client=api_client, peer=peer_channel, offset_date=offset_date))

In [6]:
oc20_files = [
    '../../data/br-telegram-UGC-question-20-run-1-2025-10-30T18-43-00-395376.json',
    '../../data/br-telegram-UGC-question-20-run-2-2025-10-30T18-43-00-624023.json',
    '../../data/br-telegram-UGC-question-20-run-3-2025-10-30T18-43-00-839447.json',
    '../../data/br-telegram-UGC-question-20-run-4-2025-10-30T18-43-01-055593.json',
    '../../data/br-telegram-UGC-question-20-run-5-2025-10-30T18-43-01-274189.json',
]
oc20_data = []
for file in oc20_files:
    with open(file, 'r') as f:
        oc20_data.append(json.load(f))

In [16]:
data_run_1 = oc20_data[0]
for other_run_data in oc20_data[1:]:
    print(data_run_1 == other_run_data)

True
True
True
True

**OC21: Is the data returned by the platform’s API consistent with the parameters and filters used in the request?**

*This item verifies whether the data extracted through the API accurately reflects the parameters and filters specified in the request. The assessment should conduct repeated test queries to confirm the consistency of results or ground the response based on recent (less than 2 years) experiments published in peer-reviewed journals.*

Test instructions: Please, develop a process that request data using different parameter to the same endpoint. If possible, test at least 5 different parameters/filters. If the platform provides less than 5, use all available parameters/filters.

Save each response in separate files.

In [ ]:
parameters = [
    {'param_name': 'offset_date', 'kwargs':{'offset_date':datetime.fromisoformat('2023-10-01T00:00:00Z')}}, # get messages before this datetime
    {'param_name': 'reverse_order', 'kwargs':{'reverse': True}}, # get messages from oldest to newest
    {'param_name': 'search', 'kwargs':{'search': 'chocolate'}}, # search for messages containing the term "chocolate"
    {'param_name': 'specific_ids', 'kwargs':{'ids': [5000, 2895, 6010, 6322]}}, # get specific messages by their ID
    {'param_name': 'offset_id', 'kwargs':{'offset_id': 6000}}, # retrieve messages posted before the one with this ID
]

peer_channel = PeerChannel(channel_id=1593453357)# object that identifies a channel

async def get_consistent_data(api_client: TelegramClient, peer: PeerChannel, parameters: list[dict], limit: int = 5):
    for idx, param in enumerate(parameters):
        index = idx + 1 
        data_dir = "../../data" # SET PATH
        filename = f"br-telegram-UGC-question-21-run-{index}-{param['param_name']}-{datetime.now().strftime('%Y-%m-%dT%H-%M-%S-%f')}.json"
        
        # implement the function here
        response = await api_client.get_messages(
            entity=peer,# object for identifying a group, channel or user
            limit=limit,# maximum number of messages to retrieve
            **param['kwargs']
        )
        
        messages = [# convert some of telethon messages fields to a JSON serializable format (e.g. datetime to isoformat)
            {
                'id': m.id,
                'peer_id': m.peer_id.channel_id,
                'date': m.date.isoformat(),
                'message': m.message
            } for m in response
        ]

        with open(f"{data_dir}/{filename}", "w") as fout:
            json.dump(messages, fout)

await asyncio.create_task(get_consistent_data(api_client=api_client, peer=peer_channel, parameters=parameters))

In [18]:
oc21_files = [
    '../../data/br-telegram-UGC-question-21-run-1-offset_date-2025-10-30T19-22-51-675408.json',
    '../../data/br-telegram-UGC-question-21-run-2-reverse_order-2025-10-30T19-22-51-908833.json',
    '../../data/br-telegram-UGC-question-21-run-3-search-2025-10-30T19-22-52-131938.json',
    '../../data/br-telegram-UGC-question-21-run-4-specific_ids-2025-10-30T19-22-52-584131.json',
    '../../data/br-telegram-UGC-question-21-run-5-offset_id-2025-10-30T19-22-52-829023.json',
]
oc21_data = []
for file in oc21_files:
    with open(file, 'r') as f:
        oc21_data.append(json.load(f))

### Checking Run 1: messages should be from before the offset date

In [24]:
for data in oc21_data[0]:
    print(datetime.fromisoformat(data['date']) < parameters[0]['kwargs']['offset_date'])

True
True
True
True
True

### Checking Run 2: messages should be ordered from oldest to newest

In [26]:
for data in oc21_data[1]:
    print(data['date'])

2021-11-09T03:04:50+00:00
2021-11-11T14:14:55+00:00
2021-11-11T14:39:12+00:00
2021-11-11T14:39:54+00:00
2021-11-11T14:40:02+00:00

### Checking Run 3: messages should contain the term "chocolate"
(the message limit was 5, but only 4 messages were returned because of the search term specified)

In [30]:
for data in oc21_data[2]:
    print('chocolate' in data['message'].lower())

True
True
True
True

### Checking Run 4: returned messages should be the ones with the specified IDs

In [33]:
parameters[3]['kwargs']['ids']

[5000, 2895, 6010, 6322]

In [35]:
for data in oc21_data[3]:
    print(data['id'])

5000
2895
6010
6322

### Checking Run 5: returned messages should be the ones with IDs before the offset ID

In [36]:
parameters[4]['kwargs']['offset_id']

6000

In [37]:
for data in oc21_data[4]:
    print(data['id'])

5999
5998
5997
5996
5995

### RELEVANCE

**OC22: Does the data extracted by the platform’s API reflect what is displayed on its user interface?**

*This item verifies whether the data returned by the API corresponds to the information displayed on the platform’s user interface at all levels of detail. The assessment should compare API responses with the user interface to confirm that key elements—such as authorship, complete content, interaction counts (e.g., comments, shares, replies), and referenced content (e.g., shares, mentions)—are fully represented.*

In [39]:
channel_url = 't.me/odespertarreserva'
async def get_gui_displayed_data(api_client: TelegramClient, channel_url: str):
    return await api_client.get_messages(
        entity=channel_url,# object for identifying a group, channel or user
        limit=10,# maximum number of messages to retrieve
    )

messages = await asyncio.create_task(get_gui_displayed_data(api_client=api_client, channel_url=channel_url))

In [67]:
screenshot_msg = messages[1]# Selecting the message corresponding to the screenshot we took from the desktop app

### Please compare the following outputs to the screenshot taken for this question. The screenshot is in **/2025/data/br-telegram-UGC-question-22-screenshot.png**

### Info about the video on the message

In [68]:
screenshot_msg.media.document.attributes[0].to_dict()

{'_': 'DocumentAttributeVideo',
 'duration': 65.458,
 'w': 640,
 'h': 360,
 'round_message': False,
 'supports_streaming': True,
 'nosound': False,
 'preload_prefix_size': None,
 'video_start_ts': None,
 'video_codec': 'h264'}

### The text message

In [69]:
print(screenshot_msg.message)

🌩

🇺🇸⚡️

Secretário do Tesouro, Scott Bessent, ouviu os argumentos orais da Suprema Corte e está OTIMISTA de que eles manterão as tarifas do Governo Donald Trump.

“Estou muito otimista, depois de ouvir as perguntas na Suprema Corte, de que a decisão sobre a IEEPA será favorável ao Presidente Trump e a esta Administração.”

#### Views, publish date (UTC, screenshot was taken in UTC-3) and author

In [71]:
screenshot_msg.views, screenshot_msg.date.isoformat(), screenshot_msg.post_author

(460, '2025-11-05T22:04:44+00:00', 'Anna Monteiro ✨️✨️🇧🇷👽🛸✨️✨️')

### User reactions (emojis)

In [72]:
screenshot_msg.reactions.to_dict()

{'_': 'MessageReactions',
 'results': [{'_': 'ReactionCount',
   'reaction': {'_': 'ReactionEmoji', 'emoticon': '👏'},
   'count': 20,
   'chosen_order': None},
  {'_': 'ReactionCount',
   'reaction': {'_': 'ReactionEmoji', 'emoticon': '👍'},
   'count': 2,
   'chosen_order': None}],
 'min': False,
 'can_see_list': False,
 'reactions_as_tags': False,
 'recent_reactions': [],
 'top_reactors': []}

**OC23: Does the platform’s API allow for filtering data based on publisher location?**

*This item verifies whether the API supports applying location-based filters to data extraction. The assessment should test the endpoint for the main content type to confirm that data on public posts can be filtered by publisher location.*

Telegram’s TDLib and core API do not provide any parameter or endpoint that allows filtering messages or posts by the publisher’s geographic location.

**OC24: Does the platform’s API allow for filtering data based on content language?**

*This item verifies whether the API allows for applying language-based filters to data extraction. The assessment should test the endpoint for the main content type to confirm that public post data can be filtered by content language.*

Telegram’s TDLib and core API do not include any parameter or method that enables filtering data based on the language of message content.

**OC25: Does the platform’s API allow for filtering data by specific time periods?**

*This item verifies whether the API allows applying temporal filters to data extraction. The assessment should test the endpoint for the main content type to confirm that public post data can be filtered by custom time ranges.*

In [6]:
min_date = datetime.fromisoformat('2025-09-29T00:00:00Z')
max_date = datetime.fromisoformat('2025-10-01T00:00:00Z')
peer_channel = PeerChannel(channel_id=1742616113)# object that identifies a channel

async def get_messages_time_range(api_client: TelegramClient, peer: PeerChannel, min_date: datetime, max_date: datetime, limit: int = 100):
    return await api_client(functions.messages.SearchRequest(
        peer=peer_channel,
        q='', # Empty string for all messages texts
        filter=InputMessagesFilterEmpty(), # Search for all message types
        # The five positional arguments required by the function:
        offset_id=0,       # Start from the beginning
        add_offset=0,      # No additional offset
        max_id=0,          # Search up to the newest message
        min_id=0,          # Search down to the oldest message
        hash=0,            # Default hash value
        min_date=min_date,
        max_date=max_date,
        limit=100
    ))

result = await asyncio.create_task(get_messages_time_range(api_client=api_client, peer=peer_channel, min_date=min_date, max_date=max_date))
result_selection = [
    {
        'channel_id': x.peer_id.channel_id,
        'date': x.date.isoformat(),
        'message_id': x.id,
        'message_type': x.to_dict()['_'],
        'message': x.message
    } for x in result.messages
]

df = pd.DataFrame(result_selection)
df.sort_values(by='date', ascending=False)

,channel_id,date,message_id,message_type,message
0,1742616113,2025-09-30T20:40:27+00:00,83526,Message,Here's Why Digital ID Is So Dangerous And What...
1,1742616113,2025-09-30T14:01:18+00:00,83525,Message,
2,1742616113,2025-09-30T13:25:02+00:00,83524,Message,https://petition.parliament.uk/petitions/722377
3,1742616113,2025-09-30T13:08:57+00:00,83523,Message,
4,1742616113,2025-09-30T12:56:15+00:00,83522,Message,"Digital ID Help Centre, to help you into slave..."
5,1742616113,2025-09-30T11:50:54+00:00,83521,Message,
6,1742616113,2025-09-30T11:42:32+00:00,83520,Message,➝ What are Rights? 🔑\n\nRights are most easily...
7,1742616113,2025-09-30T11:41:44+00:00,83519,Message,➝ Get to the Root Cause.\n\nWhat we do and who...
8,1742616113,2025-09-30T11:25:16+00:00,83518,Message,Education is the key to knowledge and freedom!...
9,1742616113,2025-09-30T02:41:59+00:00,83515,Message,https://youtu.be/4iv3qxblyI8?si=Sikow-IAUhWLUShc
10,1742616113,2025-09-30T02:39:05+00:00,83514,Message,https://youtu.be/B4I0a2rQxTI?si=xSzQuje2JnenUAYz
11,1742616113,2025-09-30T02:35:34+00:00,83513,Message,https://youtu.be/GHXdD_C5iFg?si=KG7d9pi-KcTfRblR
12,1742616113,2025-09-30T00:16:43+00:00,83512,Message,Riley Montgomery ~Welcome to :Break-The-Spell:...
13,1742616113,2025-09-30T00:16:43+00:00,83511,MessageService,None
14,1742616113,2025-09-29T23:02:09+00:00,83510,Message,
15,1742616113,2025-09-29T20:30:49+00:00,83509,Message,https://www.facebook.com/share/r/19ZdZWPEZA/
16,1742616113,2025-09-29T19:53:16+00:00,83508,Message,
17,1742616113,2025-09-29T19:53:16+00:00,83507,Message,
18,1742616113,2025-09-29T18:30:38+00:00,83506,MessageService,None
19,1742616113,2025-09-29T18:30:33+00:00,83505,Message,➝ We're Bound to Slavery by Ignorance. ⚖️\n\nP...
20,1742616113,2025-09-29T17:33:42+00:00,83504,Message,Truth is concealed in a somber yet delightful ...
21,1742616113,2025-09-29T16:55:47+00:00,83503,Message,He’s advocating CBD
22,1742616113,2025-09-29T16:51:38+00:00,83502,Message,Wow\n\nJoin\n👇🏻👇🏻\nMichael Jackson
23,1742616113,2025-09-29T14:41:05+00:00,83501,Message,Grand Theft World Podcast 254 | The Apotheosis...
24,1742616113,2025-09-29T14:27:04+00:00,83500,Message,➝ Teachability — How Teachable Are You?.\n\nTh...
25,1742616113,2025-09-29T14:26:34+00:00,83499,Message,➝ Truth is the Foundation That Leads to the He...
26,1742616113,2025-09-29T13:18:14+00:00,83498,Message,"It's 5 seconds to midnight, if you do not educ..."
27,1742616113,2025-09-29T12:27:23+00:00,83497,Message,"COVID Was a Hospital Holocaust, and the Ventil..."
28,1742616113,2025-09-29T12:26:02+00:00,83496,Message,
29,1742616113,2025-09-29T12:25:18+00:00,83495,Message,
30,1742616113,2025-09-29T10:47:15+00:00,83494,Message,https://www.weforum.org/stories/2018/05/thousa...
31,1742616113,2025-09-29T09:53:38+00:00,83493,Message,"Review of Senator Rand Paul's book, ""Deception..."
32,1742616113,2025-09-29T08:46:47+00:00,83492,Message,No to Digital ID - D5 - Q . . . We spoke about...
33,1742616113,2025-09-29T05:30:41+00:00,83491,Message,""" BESIDES the freehold estates in land, which ..."
34,1742616113,2025-09-29T05:06:39+00:00,83490,Message,...ubi jus ibi remedium... 'where there is a r...
35,1742616113,2025-09-29T03:58:17+00:00,83489,Message,https://www.facebook.com/share/v/17Hs238xKv/?m...

### TIMELINESS

**OC26: Can data from newly published content be extracted from the platform’s API in near real time?**

*This item verifies whether the API allows the collection of data from specific content within one hour of its publication. The assessment should test the endpoint for the main content type to confirm that it allows the ready extraction of recent public posts data.*

In [10]:
peer_channel = PeerChannel(channel_id=1275214093)# object that identifies a channel
async def get_recent_data(api_client: TelegramClient, peer: PeerChannel):
    collection_date = datetime.now(tz=timezone.utc).isoformat()
    response = await api_client.get_messages(
        entity=peer,# object for identifying a group, channel or user
        limit=1# maximum number of messages to retrieve
    )
    most_recent_post_date = response[0].date.isoformat()
    print("Collection date:", collection_date)
    print("Most recent post:", most_recent_post_date)
    
await asyncio.create_task(get_recent_data(api_client=api_client, peer=peer_channel))

Collection date: 2025-11-05T18:27:46.164993+00:00
Most recent post: 2025-11-05T18:18:29+00:00